version: '3.8'

services:
  # app: 
  #   image: eventoapi
  #   container_name: evento-app-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db

  db:
    container_name: mysql-db-eventoapi
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: eventoApi123
    ports:
      - "3306:3306"