version: '3.8'

services:
  db:
    container_name: mysql-db-api
    image: mysql:8.0.35
    environment:
      MYSQL_DATABASE: eventoapi_db
      MYSQL_ROOT_PASSWORD: eventoApi123
    ports:
      - "3306:3306"
    volumes:
      - "./db/create-db-tables.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db/init.sql:/docker-entrypoint-initdb.d/2.sql"